query MyLeagues {
  myLeagues {
    id
    name
    slug
    createdAt
    currentSeason {
      id
      year
      status
    }
  }
}

query LeaguePage($slug: String!, $year: Int!) {
  league(slug: $slug) {
    id
    name
    slug
    season(year: $year) {
      id
      year
      status
      teams {
        id
        name
        wins
        losses
        ties
        pointsFor
        pointsAgainst
        owner {
          id
          name
          email
        }
      }
    }
  }
}
